#!/usr/bin/env python3
"""Inline mcp/front.py + mcp/tools.py into the MCP front service's `command` in runtipi/docker-compose.yml.

Usage: python3 mcp/inline.py [--check]
The front runs on a stock, digest-pinned python image, so the app needs no image build or registry.
--check exits 1 when the compose file is out of date (CI uses this).
"""
import re
import sys
from pathlib import Path

root = Path(__file__).resolve().parent.parent
compose = root / "runtipi" / "docker-compose.yml"
src = (root / "mcp" / "front.py").read_text() + "\n\n# ---- tools for this app ----\n" + (root / "mcp" / "tools.py").read_text()
src += "\n\nif __name__ == \"__main__\":\n    asyncio.run(main())\n"
assert "$" not in src, "keep $ out of the MCP front (compose would interpolate it)"
text = compose.read_text()
pat = re.compile(r"^( *)# BEGIN MCP FRONT \(generated by mcp/inline.py\)\n\1- \|\n(.*?)\n\1# END MCP FRONT", re.S | re.M)
m = pat.search(text)
if not m:
    sys.exit("compose has no MCP FRONT markers")
ind = m.group(1)
block = "\n".join((ind + "  " + line) if line else "" for line in src.splitlines())
new = text[:m.start()] + f"{ind}# BEGIN MCP FRONT (generated by mcp/inline.py)\n{ind}- |\n{block}\n{ind}# END MCP FRONT" + text[m.end():]
if "--check" in sys.argv:
    sys.exit(0 if new == text else "runtipi/docker-compose.yml is stale: run python3 mcp/inline.py")
compose.write_text(new)
print("updated", compose.relative_to(root))
